function res = getPrecondTG(x,P,rvec_in,rvec_out,nn,weights,Ci,vars,R)
% GETPRECONDTG - Apply action of preconditioned and symmetrized combined DLP SLP
% operator (TG+(TG)')/2.
%
% Input arguments:
% x        - input vector of source strengths (stacked per body)
% P        - number of patches
% rvec_in  - proxy source node coordinates (stacked)
% rvec_out - outer target node coordinates (stacked)
% nn       - normal vectors at outer nodes
% weights  - quadrature nodes at target nodes (stacked) for one coordinate
% Ci       - one body preconditioning matric 
% vars     - struct of parameters passed to flow/traction routines
% R        - optional 1 x P cell array of body rotations. If supplied, the
%            one-body preconditioner block is rotated into each body's local frame.
%
% Output arguments:
% res      - preconditioned vector (same layout as x)

if nargin == 0
    self_test;
    return;
end

%dense implementation that should generate the same result: 
% S = stokes_SLP_mat(rvec_in,rvec_out); 
% A  = TW*S;
% B = (A+A')/2;
% C = kron(eye(P),Ci);
% B_precond = C*B*C';
% res = B_precond*x;

if nargin < 9
    R = [];
end

N = length(rvec_in)/P;
M = length(rvec_out)/P;

%% Prepare weights
w = weights(:)';
ww = repmat(w,3,1);
%ww = ww(:); 
%% Apply preconditioner for each body
mu = zeros(3*N*P,1); 
for k = 1:P
    idx = (k-1)*3*N+1:k*3*N;
    if isempty(R)
        mu(idx) = Ci'*x(idx);
    else
        x_local = rotate_vector(x(idx), R{k}.');
        mu(idx) = rotate_vector(Ci'*x_local, R{k});
    end
end

%% first term
% S\mu
uS = getStokesletFlow(mu, rvec_in, rvec_out, vars);
%uTS2= T*uS; Same thing with dense linear algebra

% Compute DLP velocity field with S\mu as input
fmm_tmp = vars.fmm; 
vars.fmm = 0;
uS = ww(:).*uS;
uTS = getStressletFlow(rvec_out,rvec_in,nn,uS,M*P,vars);
vars.fmm = fmm_tmp; % too slow to use fmm for traction evaluation due to 
% how traction is computed via gradu and p

%% second term
%T = stokes_DLP(rvec_out,rvec_in,nn); 
%uT = W'*T'*mu;
% Traction due to single-layer of mu
%uT = getTractionDirectSLP(rvec_in, rvec_out, nn, mu);

%attemp at making faster implementation
fmm_tmp = vars.fmm; 
vars.fmm = 0; 
uT = getTractionFast(mu,rvec_in,rvec_out,nn,vars);
vars.fmm = fmm_tmp; 
uT = ww(:).*uT; 

% Stokeslet flow field generated by the traction field (swap source/target)
uST = getStokesletFlow(uT, rvec_out, rvec_in, vars); 
%swap order of source and target here as we want the action of S'

%% Symmetric combination of the two terms
uAll = 0.5*(uTS+uST);
res = zeros(3*N*P,1);
% Project result back to global basis, again using the 1 body
% preconditioner
for k = 1:P
    idx = (k-1)*3*N+1:k*3*N;
    if isempty(R)
        res(idx) = Ci*uAll(idx);
    else
        u_local = rotate_vector(uAll(idx), R{k}.');
        res(idx) = rotate_vector(Ci*u_local, R{k});
    end
end



end

function self_test()

rng(4);

P = 2;
E0 = [0.7 0.45 1.1];
delta = 0.8;
sep = 0.12;
N1 = 12;
N2 = 10;

[~,R,qvec,~] = ellipsoid_cluster(E0,P,delta);
R{1} = eye(3);

alpha = 0.47;
beta = -0.61;
Rz = [cos(alpha) -sin(alpha) 0; sin(alpha) cos(alpha) 0; 0 0 1];
Ry = [cos(beta) 0 sin(beta); 0 1 0; -sin(beta) 0 cos(beta)];
R{2} = Rz * Ry;

[rvec_in,rvec_out,~,~,~,w,n_out] = getEllipsoidGrids(E0,P,delta,N1,N2,sep,R,qvec);

M = size(rvec_out,1)/P;
N = size(rvec_in,1)/P;

C = getSymTWS(rvec_out,rvec_in,n_out,w);
Ci_body = getSymTWS(rvec_out(1:M,:),rvec_in(1:N,:),n_out(1:M,:),w(1:M));

[Vi,Di] = eig(Ci_body);
di = diag(Di);
trunc = 1e-12;
ind = find(real(di) > trunc);
diff_set = setdiff(1:numel(di),ind);
dsqrt = sqrt(di);
dsqrt_inv = 1./dsqrt;
dsqrt_inv(diff_set) = 0;
Pi = diag(dsqrt_inv) * Vi';

Pglob = zeros(3*N*P);
Pglob_wrong = zeros(3*N*P);
for k = 1:P
    idx = (k-1)*3*N + (1:3*N);
    Pglob(idx,idx) = rotate_block(Pi,R{k});
    Pglob_wrong(idx,idx) = Pi;
end

vars.fmm = 0;
vars.eps = 1e-10;
x = randn(3*N*P,1);

y_fast = getPrecondTG(x,P,rvec_in,rvec_out,n_out,w,Pi,vars,R);
y_dense = Pglob * C * Pglob' * x;
y_wrong = Pglob_wrong * C * Pglob_wrong' * x;

rel_err = norm(y_fast - y_dense) / max(norm(y_dense),eps);
rel_wrong = norm(y_fast - y_wrong) / max(norm(y_fast),eps);

fprintf('getPrecondTG self-test:\n');
fprintf('  P = %d, N = %d, M = %d\n', P, N, M);
fprintf('  rel err (matvec vs dense rotated precond) = %.3e\n', rel_err);
fprintf('  rel diff vs unrotated block precond       = %.3e\n', rel_wrong);

if rel_err > 1e-10
    error('getPrecondTG:self_test', ...
        'Rotation-aware preconditioned matvec did not match the dense reference.');
end

fprintf('  self-test passed.\n');

end

function B_rot = rotate_block(B, R)
npts = size(B,1) / 3;
Rbig = kron(eye(npts), R);
B_rot = Rbig * B * Rbig';
end
