function res = getPrecondTG(x,P,rvec_in,rvec_out,nn,Ci,vars)
% GETPRECONDTG - Apply action of preconditioned and symmetrized combined DLP SLP
% operator (TG+(TG)')/2.
%
% Input arguments:
% x        - input vector of source strengths (stacked per body)
% P        - number of patches
% rvec_in  - proxy source node coordinates (stacked)
% rvec_out - outer target node coordinates (stacked)
% nn       - normal vectors at outer nodes
% Ci       - one body preconditioning matric 
% vars     - struct of parameters passed to flow/traction routines
%
% Output arguments:
% res      - preconditioned vector (same layout as x)

%dense implementation that should generate the same result: 
% S = stokes_SLP_mat(rvec_in,rvec_out); 
% A  = T*S;
% B = (A+A')/2;
% C = kron(eye(P),Ci);
% B_precond = C*B*C';
% res = B_precond*x;

N = length(rvec_in)/P;
M = length(rvec_out)/P;

%% Apply preconditioner for each body
mu = zeros(3*N*P,1); 
for k = 1:P
    mu((k-1)*3*N+1:k*3*N) = Ci'*x((k-1)*3*N+1:k*3*N);
end

%% first term
% S\mu
uS = getStokesletFlow(mu, rvec_in, rvec_out, vars);
%uTS2= T*uS; Same thing with dense linear algebra

% Compute DLP velocity field with S\mu as input
fmm_tmp = vars.fmm; 
vars.fmm = 0;
uTS = getStressletFlow(rvec_out,rvec_in,nn,uS,M*P,vars);
vars.fmm = fmm_tmp; % too slow to use fmm for traction evaluation due to 
% how traction is computed via gradu and p

%% second term
%T = stokes_DLP(rvec_out,rvec_in,nn); 
%uT = T'*mu;
% Traction due to single-layer of mu
%uT = getTractionDirectSLP(rvec_in, rvec_out, nn, mu);

%attemp at making faster implementation
fmm_tmp = vars.fmm; 
vars.fmm = 0; 
uT = getTractionFast(mu,rvec_in,rvec_out,nn,vars);
vars.fmm = fmm_tmp; 

% Stokeslet flow field generated by the traction field (swap source/target)
uST = getStokesletFlow(uT, rvec_out, rvec_in, vars); 
%swap order of source and target here as we want the action of S'

%% Symmetric combination of the two terms
uAll = 0.5*(uTS+uST);
res = zeros(3*N*P,1);
% Project result back to global basis, again using the 1 body
% preconditioner
for k = 1:P
    res((k-1)*3*N+1:k*3*N) = Ci*uAll((k-1)*3*N+1:k*3*N);
end

res = M/(4*pi)*res;

end
